import reflex as rx

def menu_year() -> rx.Component:
    return rx.container(
        rx.hstack(
            rx.button(
                "Year 1", 
                padding="20px", 
                background_color="#42798F",
                size="2",  
                weight="bold",
                color="white",  
                width="180px", 
                height="180px",
                border_radius="20px",
            ), 
            rx.button(
                "Year 2", 
                padding="20px", 
                background_color="#42798F",
                size="2", 
                weight="bold",
                color="white",  
                width="180px", 
                height="180px",
                border_radius="20px",
            ),
            justify="center", 
            align_items="center",  
            width="100%",  
        ),
        rx.hstack(
            rx.button(
                "Year 3", 
                padding="20px", 
                background_color="#42798F",
                size="2", 
                weight="bold",
                color="white",  
                width="180px", 
                height="180px",
                border_radius="20px",
            ),
            rx.button(
                "Year 4", 
                padding="20px", 
                background_color="#42798F",
                size="2",
                weight="bold",
                color="white",  
                width="180px", 
                height="180px",
                border_radius="20px",
            ),
            margin_top="20px",
            justify="center",  
            align_items="center",  
            width="100%", 
        ),
        width="100%", 
        align_items="center",  
    )
